project:
  type: website

website:
  title: "Comparing `mgcv::bam` with `glmmLDTS`"
  navbar:
    left:
      - href: index.qmd
        text: Article

format:
  html:
    theme: cosmo
    linestretch: 1.6
    css: styles.css
    toc: true

editor: visual

